### ISSUE TITLE
The documentation on Crate. io is not the same as that on Github

### ISSUE THREAD

**Issue by QingyaoLin** [craciuncezar/git-smart-checkout#4]
According to the documentation on Crate. IO, I tried to install the CREATE today, but it showed  --> could not find `smart-checkout` in registry `crates-io` with version `*`

steps:
1. First : `cargo install  smart-checkout`
```    
error: could not find `smart-checkout` in registry `crates-io` with version `*`
```
2. then: cargo search  smart-checkout
```
smart-checkout = "0.0.0"        # A better way of switching git branches.
git-smart-checkout = "0.1.0"    # A better way of switching git branches.
```
3. so:  The installation command should be `cargo install git-smart-checkout`  , rather than `cargo install  smart-checkout`
```
💀 97% 🚀 ❯❯❯ cargo install git-smart-checkout
    Updating crates.io index
  Downloaded git-smart-checkout v0.1.0
  Downloaded 1 crate (2.0 MB) in 4.54s
```
In fact, the Github documentation says cargo install Git-smart-checkout should be used.

Crate.io is not consistent with github.

**Comment by craciuncezar** [comment]
That's correct, thanks for pointing it out 👍 this should be fixed now
